### ISSUE TITLE
It prefers choosing NotoColorEmoji-old.ttf than NotoColorEmoji.ttf now.

### ISSUE THREAD

**Issue by Ketagalan** [Magisk-Modules-Repo/magisk-notocoloremoji-replacer#1]
Should the following be not here in fonts.xml?
```
<family lang="und-Zsye">
<font weight="400" style="normal">NotoColorEmoji-old.ttf</font>
</family>
```

It seems to cause the issue which sets old emoji in priority.

**Comment by simonsmh** [comment]
In that case we can get blob back again. That's what it should be.

**Comment by simonsmh** [comment]
I use https://emojipedia.org/emoji-5.0/ to have this test, and it shows that it's working at the same time. emoji 4- are all blobs emoji, but emoji 5 is not.

**Comment by Ketagalan** [comment]
But on my phone it shows the egg-heads emoji and not the Oreo one… How about put the section of "NotoColorEmoji.ttf" in front of "NotoColorEmoji-old.ttf"?

**Comment by simonsmh** [comment]
Then you will get All Android O emoji which was did by other modules.

**Comment by Ketagalan** [comment]
It's a bit difficult to understand. I set "NotoColorEmoji.ttf" in front of "NotoColorEmoji-old.ttf", it shows Oreo emojis (which is 6.92MB in your module) in priority correctly. As your design, it may work normally with installation via Magisk directly?

**Comment by simonsmh** [comment]
To make it clear, I don't like the new design of Android O emoji. So this module was designed to make it possible to use Android N emoji as much as possible and at the same time, do not drop support of more Unicode characters.

**Comment by Ketagalan** [comment]
Got it, so if I prefer Oreo emojis, I can change the two sections by myself, or it will be primary for Nougat emojis over Oreo emojis by the module's default!

**Comment by simonsmh** [comment]
Yes, you are right, so I prefer you to choose https://github.com/Magisk-Modules-Repo/AndroidO-NotoColorEmojiReplacer and not my module.
